public class DemoClass {
    
    public DemoClass(){
        
        system.debug('Hi rEMO'); // TEST
        String name ='Ram 444'; //666
        Integer testre =10000;
        //DOBULE THI VALUE
        
    }
    
    public void printMethod(){
        //system.debug('Hi MR 555');
        //hello
    }
        public void printMethod3(){
        system.debug('Hi MR 3455');
            //hello
    }

}